language: go
sudo: false
go:
  - 1.11.x
env:
  global:
    - GO111MODULE=on
install:
  - go get -v .

before_script:
  - go vet -v ./...
script:
  - echo $TRAVIS_GO_VERSION; go test -race -v -timeout 60s ./...